import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/NavbarServer";
import i18nConfig from "@/i18nConfig";
import { dir } from "i18next";
import TranslationsProvider from "@/components/layout/TranslationsProvider";
import initTranslations from "@/app/i18n";
import ClientProviders from "@/components/layout/ClientProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

const namespaces = ["home"];

export default async function RootLayout(props) {
  const { children } = props;
  const params = await getParams(props);
  const locale = params.locale;

  const { resources } = await initTranslations(locale, namespaces);

  return (
    <html lang={locale} dir={dir(locale)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProviders>
          <TranslationsProvider
            locale={locale}
            namespaces={namespaces}
            resources={resources}
          >
            <div className="mx-auto max-w-screen-lg h-screen flex flex-col">
              <Navbar locale={locale} />
              <div className="flex-grow">{children}</div>
            </div>
          </TranslationsProvider>
        </ClientProviders>
      </body>
    </html>
  );
}

async function getParams(props) {
  return props.params;
}
